# Dotter global configuration file
# This file defines packages and their file deployment rules

[helpers]

# Default package for all systems
[default]
depends = ["ssh"]

[default.files]

# Windows-specific package
[windows]
depends = ["ssh"]

[windows.files]

# Linux-specific package
[linux]
depends = ["ssh"]

[linux.files]

# SSH configuration package (cross-platform)
[ssh]
depends = []

[ssh.files]
"ssh/config" = "~/.ssh/config"
"ssh/conf.d/config" = "~/.ssh/conf.d/config"
"ssh/conf.d/repos" = "~/.ssh/conf.d/repos"

# Deploy individual SSH config files (excluding .git submodule files)
"ssh/conf.d/hosts/develop/config" = "~/.ssh/conf.d/hosts/develop/config"
"ssh/conf.d/hosts/develop/atsugi" = "~/.ssh/conf.d/hosts/develop/atsugi"
"ssh/conf.d/hosts/develop/sco" = "~/.ssh/conf.d/hosts/develop/sco"

"ssh/conf.d/hosts/lagune/config" = "~/.ssh/conf.d/hosts/lagune/config"
